### ISSUE TITLE
Enable Run test suite and Linter as workflow

### ISSUE THREAD

**Issue by sharpener6** [Citi/scaler#7]
This will requires strict checking on PEP8 and mypy errors and of course all the unit test cases, please add following to actions, all the mypy/flake8 arguments should be defined in pyproject.toml:

```yaml
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pyproject-flake8 mypy
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pflake8 .
      - name: Lint with MyPy
        run: |
          mypy .
      - name: Run python unittest
        run: |
          python -m unittest discover -v tests
```
